training_dataset:
  name: imagenet
  tfrecord_dir: /media/homes/ujjwal/datasets/imagenet2012/tfrecords
  batch_size: 128
val_dataset:
  name: imagenet
  tfrecord_dir: /media/homes/ujjwal/datasets/imagenet2012/tfrecords
  batch_size: 128
preprocessing_training:
  _target_: augmentations.ops.AugmentationList
  transforms:
  - _target_: augmentations.ops.ResizeSmallest
    p: 1.0
    resize_dim: 256
  - _target_: augmentations.ops.RandomCrop
    p: 1.0
    crop_height: 224
    crop_width: 224
  - _target_: augmentations.ops.HorizontalFlip
    p: 0.5
  - _target_: augmentations.ops.RandomRotate
    p: 0.3
    min_rot: -15.0
    max_rot: 15.0
    fill_mode: "reflect"
  - _target_: augmentations.ops.RandomTranslation
    p: 0.3
    height_factor_min: -0.2
    height_factor_max: 0.2
    width_factor_min: -0.2
    width_factor_max: 0.2
    fill_mode: "reflect"
  - _target_: augmentations.ops.Grayscale
    p: 0.2
  - _target_: augmentations.ops.BrightnessContrast
    p: 0.3
  - _target_: augmentations.ops.NormalizeImageRange
    p: 1.0
preprocessing_val:
  _target_: augmentations.ops.AugmentationList
  transforms:
  - _target_: augmentations.ops.ResizeSmallest
    p: 1.0
    resize_dim: 256
  - _target_: augmentations.ops.CenterCrop
    p: 1.0
    crop_height: 224
    crop_width: 224
  - _target_: augmentations.ops.NormalizeImageRange
    p: 1.0
backbone:
  name: resnet_50
  model_id: 50
  depth_multiplier: 1.0
  stem_type: v0
  resnetd_shortcut: false
  replace_stem_max_pool: false
  se_ratio: null
  init_stochastic_depth_rate: 0.0
  scale_stem: true
  activation: relu
  use_sync_bn: false
  norm_momentum: 0.99
  norm_epsilon: 0.001
  kernel_initializer: VarianceScaling
  l2_reg: 0.0005
  l2_bias_reg: null
  bn_trainable: true
wandb:
  job_type: "train"
  dir: null
  config: null
  project: "waldo"
  entity: null
  reinit: null
  tags: null
  group: "backbones2d"
  name: "resnet50_trial"
  notes: null
  magic: null
  config_exclude_keys: null
  config_include_keys: null
  anonymous: null
  mode: null
  allow_val_change: null
  resume: null
  force: null
  tensorboard: null
  sync_tensorboard: null
  monitor_gym: null
  save_code: null
  id: null
  settings: null
experiment_root_dir:  /media/homes/ujjwal/research-2023/waldo/experiments
model_dir:  /media/homes/ujjwal/research-2023/waldo/experiments/models
log_dir:  /media/homes/ujjwal/research-2023/waldo/experiments/logs
max_checkpoints_to_keep: 10
num_classes: 1000
input_height: 224
input_width: 224
optimizer:
  name: "sgd"
  lr_schedule:
    name: piecewise_constant
    boundaries:
      - 10000
      - 30000
      - 80000
    values:
      - 0.0005
      - 0.00025
      - 0.000125
      - 0.0000625
  momentum: 0.9
checkpoint_name: resnet_50_imagenet
log_to_wandb: true
training_epochs: 150
log_steps: 500
restore_from_epoch: null
